\set libfile '\''`pwd`'/ldblink.so\''
CREATE OR REPLACE LIBRARY ldblink AS :libfile LANGUAGE 'C++';
CREATE OR REPLACE TRANSFORM FUNCTION dblink AS LANGUAGE 'C++' NAME 'DBLinkFactory' LIBRARY ldblink FENCED;
GRANT EXECUTE ON TRANSFORM FUNCTION dblink() TO PUBLIC;
GRANT USAGE ON LIBRARY ldblink TO PUBLIC;
